# ======================
# DATABASE SQLITE
# ======================
spring.datasource.url=jdbc:sqlite:C:/RepoDestista/Dentista/ProyectoWilsonBack/database/smilecare.db?date_string_format=yyyy-MM-dd
spring.datasource.driver-class-name=org.sqlite.JDBC

# SQLite no usa user/pass
spring.datasource.username=
spring.datasource.password=

# Dialecto SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de fechas para SQLite
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.type.preferred_instant_jdbc_type=TIMESTAMP

# IMPORTANTE: DESACTIVAR SQL init
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

# ======================
# SERVER
# ======================
server.port=8080

# Desactivar consola H2
spring.h2.console.enabled=false